# 笔记列表
GET http://localhost:10020/notes/note?pageNum=1&pageSize=2&categoryId=14

###

# 新增、修改笔记
PUT http://localhost:10020/notes/note
Content-Type: application/json

{
  "name": "Go+Python混合开发",
  "description": "Java程序员的福音"
}

###

# 分类列表
GET http://localhost:10020/notes/category/all